# Generated by Django 3.1.4 on 2021-01-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'ММИЛ вопрос',
                'verbose_name_plural': 'ММИЛ вопросы',
            },
        ),
        migrations.CreateModel(
            name='MMPIScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_inverted', models.BooleanField(default=False)),
                ('negative_keys', models.ManyToManyField(blank=True, related_name='negative_keys', to='candidate_tests.MMPIQuestion')),
                ('positive_keys', models.ManyToManyField(blank=True, related_name='positive_keys', to='candidate_tests.MMPIQuestion')),
            ],
            options={
                'verbose_name': 'ММИЛ шкала',
                'verbose_name_plural': 'ММИЛ шкалы',
            },
        ),
    ]
