# Generated by Django 3.1.4 on 2021-01-29 11:11

import candidate_tests.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210125_1724'),
        ('candidate_tests', '0002_testingsession_testingsessiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingsession',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_sessions', to='users.candidate'),
        ),
        migrations.CreateModel(
            name='TestingSessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Pending start', 'Pending start')], default='Pending start', max_length=100)),
                ('context', models.JSONField(blank=True, default=candidate_tests.utils.get_state_context_default_value)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Состояние сессии',
                'verbose_name_plural': 'Состояния сесий',
            },
        ),
    ]
