# Generated by Django 3.1.4 on 2021-01-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0003_auto_20210129_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=50)),
                ('m', models.PositiveIntegerField()),
                ('delta', models.PositiveIntegerField()),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_balls_tables', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'Tаблица T-баллов',
                'verbose_name_plural': 'Таблицы T-баллов',
                'unique_together': {('scale', 'gender')},
            },
        ),
    ]
