# Generated by Django 3.1.4 on 2021-02-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0004_tballstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmpiscale',
            name='name',
            field=models.CharField(choices=[('L', 'L'), ('F', 'F'), ('K', 'K'), ('Hs', 'Hs'), ('D', 'D'), ('Hy', 'Hy'), ('Pd', 'Pd'), ('Mm', 'Mm'), ('Mf-m', 'Mf-m'), ('Pa', 'Pa'), ('Pt', 'Pt'), ('Sc', 'Sc'), ('Ma', 'Ma'), ('Si', 'Si')], max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='mmpiquestion',
            name='id',
        ),
        migrations.AlterField(
            model_name='mmpiquestion',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
