# Generated by Django 3.1.4 on 2021-02-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0005_auto_20210201_0855'),
    ]

    operations = [

    ]
