# Generated by Django 3.1.4 on 2021-02-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0006_auto_20210201_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPITestingUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=100)),
            ],
            options={
                'verbose_name': 'Ответ пользователя на MMPI вопрос',
                'verbose_name_plural': 'Ответы пользователей на MMPI вопросы',
            },
        ),
        migrations.AlterField(
            model_name='testingsessionstate',
            name='state',
            field=models.CharField(choices=[('PENDING_START', 'PENDING_START'), ('MMPI_TEST', 'MMPI_TEST')], default='PENDING_START', max_length=100),
        ),
        migrations.CreateModel(
            name='MMPITestingUserAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='answers', through='candidate_tests.MMPITestingUserAnswer', to='candidate_tests.MMPIQuestion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MMPI_testing_answer_list', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Список ответов MMPI тестирования',
                'verbose_name_plural': 'Списки ответов MMPI тестирования',
            },
        ),
        migrations.AddField(
            model_name='mmpitestinguseranswer',
            name='answer_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.mmpitestinguseranswerlist'),
        ),
        migrations.AddField(
            model_name='mmpitestinguseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.mmpiquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='mmpitestinguseranswer',
            unique_together={('answer_list', 'question')},
        ),
    ]
