# Generated by Django 3.1.4 on 2021-02-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0007_auto_20210202_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericLogicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('point', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Числовая логика вариант ответа',
                'verbose_name_plural': 'Числовая логика варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='NumericLogicQuestion',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Числовая логика вопрос',
                'verbose_name_plural': 'Числовая логика вопросы',
            },
        ),
        migrations.CreateModel(
            name='NumericLogicUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.numericlogicanswer')),
            ],
            options={
                'verbose_name': 'Числовая логика ответ пользователья',
                'verbose_name_plural': 'Числовая логика ответы пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='mmpitestinguseranswer',
            options={'verbose_name': 'ММИЛ ответ пользователья', 'verbose_name_plural': 'ММИЛ ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='mmpitestinguseranswerlist',
            options={'verbose_name': 'ММИЛ список ответов пользователя', 'verbose_name_plural': 'ММИЛ списки ответов пользователей'},
        ),
        migrations.AlterField(
            model_name='mmpitestinguseranswer',
            name='answer',
            field=models.CharField(choices=[(1, 'Да'), (2, 'Нет')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testingsessionstate',
            name='state',
            field=models.CharField(choices=[('PENDING_START', 'PENDING_START'), ('MMPI_TEST', 'MMPI_TEST'), ('NUMERIC_LOGIC', 'NUMERIC_LOGIC')], default='PENDING_START', max_length=100),
        ),
        migrations.AlterField(
            model_name='tpointstable',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.CreateModel(
            name='NumericLogicUserAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(through='candidate_tests.NumericLogicUserAnswer', to='candidate_tests.NumericLogicQuestion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_logic_user_answer_list', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Числовая логика список ответов пользователя',
                'verbose_name_plural': 'Числовая логика списки ответов пользователей',
            },
        ),
        migrations.AddField(
            model_name='numericlogicuseranswer',
            name='answer_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.numericlogicuseranswerlist'),
        ),
        migrations.AddField(
            model_name='numericlogicuseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.numericlogicquestion'),
        ),
        migrations.AddField(
            model_name='numericlogicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidate_tests.numericlogicquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='numericlogicuseranswer',
            unique_together={('answer_list', 'question')},
        ),
    ]
