# Generated by Django 3.1.4 on 2021-02-03 16:42
from django.db import migrations

from candidate_tests.utils import constants, testing_data_parser


def numeric_logic_questions(apps, schema_editor):
    NumericLogicQuestion = apps.get_model('candidate_tests', 'NumericLogicQuestion')
    NumericLogicAnswer = apps.get_model('candidate_tests', 'NumericLogicAnswer')

    questions = testing_data_parser.parse_logic_test_file('numeric_logic_questions.xlsx')

    for q in questions:
        question, _ = NumericLogicQuestion.objects.update_or_create(
            number=q['id'],
            question=q['question'],
        )
        for a in q['answers']:
            NumericLogicAnswer.objects.update_or_create(
                question=question,
                answer=a['answer'],
                point=a['point'],
            )


class Migration(migrations.Migration):
    dependencies = [
        ('candidate_tests', '0008_auto_20210204_0808'),
    ]
    operations = [
        migrations.RunPython(numeric_logic_questions)
    ]