# Generated by Django 3.1.4 on 2021-02-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0009_auto_20210204_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalLogicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('point', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Вербальная логика вариант ответа',
                'verbose_name_plural': 'Вербальная логика варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='VerbalLogicQuestion',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Вербальная логика вопрос',
                'verbose_name_plural': 'Вербальная логика вопросы',
            },
        ),
        migrations.CreateModel(
            name='VerbalLogicUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.verballogicanswer')),
            ],
            options={
                'verbose_name': 'Вербальная логика ответ пользователья',
                'verbose_name_plural': 'Вербальная логика ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='VerbalLogicUserAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(through='candidate_tests.VerbalLogicUserAnswer', to='candidate_tests.VerbalLogicQuestion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verbal_logic_user_answer_list', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Вербальная логика список ответов пользователя',
                'verbose_name_plural': 'Вербальная логика списки ответов пользователей',
            },
        ),
        migrations.AddField(
            model_name='verballogicuseranswer',
            name='answer_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.verballogicuseranswerlist'),
        ),
        migrations.AddField(
            model_name='verballogicuseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.verballogicquestion'),
        ),
        migrations.AddField(
            model_name='verballogicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidate_tests.verballogicquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='verballogicuseranswer',
            unique_together={('answer_list', 'question')},
        ),
    ]
