# Generated by Django 3.1.4 on 2021-02-04 12:02

from django.db import migrations

from candidate_tests.utils import constants, testing_data_parser


def verbal_logic_questions(apps, schema_editor):
    VerbalLogicQuestion = apps.get_model('candidate_tests', 'VerbalLogicQuestion')
    VerbalLogicAnswer = apps.get_model('candidate_tests', 'VerbalLogicAnswer')

    questions = testing_data_parser.parse_logic_test_file('verbal_logic_questions.xlsx')

    for q in questions:
        question, _ = VerbalLogicQuestion.objects.update_or_create(
            number=q['id'],
            question=q['question'],
        )
        for a in q['answers']:
            VerbalLogicAnswer.objects.update_or_create(
                question=question,
                answer=a['answer'],
                point=a['point'],
            )


class Migration(migrations.Migration):
    dependencies = [
        ('candidate_tests', '0010_auto_20210204_1201'),
    ]
    operations = [
        migrations.RunPython(verbal_logic_questions)
    ]