# Generated by Django 3.1.4 on 2021-02-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0011_auto_20210204_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVerbalLogicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Невербальная логика ответ',
                'verbose_name_plural': 'Невербальная логика ответы',
            },
        ),
        migrations.CreateModel(
            name='NonVerbalLogicAnswerOption',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Невербальная логика вариант ответа',
                'verbose_name_plural': 'Невербальная логика варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='NonVerbalLogicQuestion',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('answer_options', models.ManyToManyField(related_name='questions', through='candidate_tests.NonVerbalLogicAnswer', to='candidate_tests.NonVerbalLogicAnswerOption')),
            ],
            options={
                'verbose_name': 'Невербальная логика вопрос',
                'verbose_name_plural': 'Невербальная логика вопросы',
            },
        ),
        migrations.CreateModel(
            name='NonVerbalLogicUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.nonverballogicanswer')),
            ],
            options={
                'verbose_name': 'Невербальная логика ответ пользователья',
                'verbose_name_plural': 'Невербальная логика ответы пользователей',
            },
        ),
        migrations.AlterField(
            model_name='testingsessionstate',
            name='state',
            field=models.CharField(choices=[('PENDING_START', 'PENDING_START'), ('MMPI', 'MMPI'), ('NUMERIC_LOGIC', 'NUMERIC_LOGIC'), ('VERBAL_LOGIC', 'VERBAL_LOGIC'), ('NON_VERBAL_LOGIC', 'NON_VERBAL_LOGIC')], default='PENDING_START', max_length=100),
        ),
        migrations.AlterField(
            model_name='testingsessiontoken',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='candidate_tests.testingsession'),
        ),
        migrations.CreateModel(
            name='NonVerbalLogicUserAnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(through='candidate_tests.NonVerbalLogicUserAnswer', to='candidate_tests.NonVerbalLogicQuestion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_verbal_logic_user_answer_list', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Невербальная логика список ответов пользователя',
                'verbose_name_plural': 'Невербальная логика списки ответов пользователей',
            },
        ),
        migrations.AddField(
            model_name='nonverballogicuseranswer',
            name='answer_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.nonverballogicuseranswerlist'),
        ),
        migrations.AddField(
            model_name='nonverballogicuseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.nonverballogicquestion'),
        ),
        migrations.AddField(
            model_name='nonverballogicanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.nonverballogicansweroption'),
        ),
        migrations.AddField(
            model_name='nonverballogicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidate_tests.nonverballogicquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='nonverballogicuseranswer',
            unique_together={('answer_list', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='nonverballogicanswer',
            unique_together={('question', 'answer')},
        ),
    ]
