# Generated by Django 3.1.4 on 2021-02-06 18:33

from django.db import migrations

from candidate_tests.utils import constants, testing_data_parser


def prof_interests_scales(apps, schema_editor):
    ProfInterestsScale = apps.get_model('candidate_tests', 'ProfInterestsScale')

    scales = testing_data_parser.parse_prof_interests_scales()

    for s in scales:
        scale, _ = ProfInterestsScale.objects.update_or_create(
            number=s['number'],
            name=s['name'],
            description=s['description'],
        )


def prof_interests_questions(apps, schema_editor):
    ProfInterestsQuestion = apps.get_model('candidate_tests', 'ProfInterestsQuestion')
    ProfInterestsScale = apps.get_model('candidate_tests', 'ProfInterestsScale')

    questions = testing_data_parser.parse_prof_interests_questions()

    for q in questions:
        scale = ProfInterestsScale.objects.get(name=q['scale'])
        question_data = {
            'number': q['id'],
            'question': 'Распределить 8 баллов между вариантами деятельности в компании '
                     'по степени привлекательности для себя (предыдущий опыт можно не учитывать). '
                     'Чем Вам в принципе было бы интересно заниматься? Вы можете поставить 8 баллов одному типу деятельности '
                     'или примерно равномерно распределить между всеми вариантами.',
            'points': 8,
        }
        question, _ = ProfInterestsQuestion.objects.get_or_create(**question_data)
        question.answers.create(
            scale=scale,
            answer=q['answer'],
        )
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0013_auto_20210207_1426'),
    ]

    operations = [
        migrations.RunPython(prof_interests_scales),
        migrations.RunPython(prof_interests_questions),
    ]
