# Generated by Django 3.1.4 on 2021-02-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0015_auto_20210210_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfInterestsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('answer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='candidate_tests.profinterestsuseranswerlist')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_tests.profinterestsscale')),
            ],
            options={
                'verbose_name': 'Проф. интересы результат тестирования',
                'verbose_name_plural': 'Проф. интересы результаты тестирования',
                'unique_together': {('answer_list', 'scale')},
            },
        ),
    ]
