# Generated by Django 3.1.4 on 2021-02-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0017_auto_20210210_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmpitestinguseranswer',
            name='answer',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')]),
        ),
        migrations.CreateModel(
            name='MMPITestingUserRowPointsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('answer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_points', to='candidate_tests.mmpitestinguseranswerlist')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_points', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ сырые баллы пользователя',
                'verbose_name_plural': 'ММИЛ сырые баллы пользователей',
                'unique_together': {('answer_list', 'scale')},
            },
        ),
    ]
