# Generated by Django 3.1.4 on 2021-02-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0018_auto_20210211_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPITestingUserRawPointsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('answer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_points', to='candidate_tests.mmpitestinguseranswerlist')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_points', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ сырые баллы пользователя',
                'verbose_name_plural': 'ММИЛ сырые баллы пользователей',
                'unique_together': {('answer_list', 'scale')},
            },
        ),
        migrations.DeleteModel(
            name='MMPITestingUserRowPointsResult',
        ),
    ]
