# Generated by Django 3.1.4 on 2021-02-14 19:24

from django.db import migrations, models
import django.db.models.deletion

from candidate_tests.utils import testing_data_parser


def MMPI_scales_description(apps, schema_editor):
    MMPIScale = apps.get_model('candidate_tests', 'MMPIScale')
    MMPIScaleDescription = apps.get_model('candidate_tests', 'MMPIScaleDescription')
    descriptions = testing_data_parser.parse_MMPI_scales_description()

    for d in descriptions:
        scales = MMPIScale.objects.filter(verbose_name=d['verbose_name'])
        d.pop('verbose_name')
        for s in scales:
            MMPIScaleDescription.objects.update_or_create(
                scale=s,
                **d,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0021_auto_20210214_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIScaleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.PositiveIntegerField()),
                ('to_point', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('description_detail', models.TextField(blank=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ шкалы описание',
                'verbose_name_plural': 'ММИЛ шкалы описание',
            },
        ),
        migrations.RunPython(MMPI_scales_description),
    ]
