# Generated by Django 3.1.4 on 2021-02-15 15:56

from django.db import migrations, models
import django.db.models.deletion

from candidate_tests.utils import testing_data_parser


def create_motivators_destructors(apps, schema_editor, sheet_name):
    MMPIScale = apps.get_model('candidate_tests', 'MMPIScale')
    model_to_create = apps.get_model(
        'candidate_tests', 
        model_name='MMPIMotivator' if sheet_name == 'Motivators' else 'MMPIDestructor',
    )
    values = testing_data_parser.parse_MMPI_motivators_destructors(sheet_name)

    for i in values:
        scales = MMPIScale.objects.filter(name=i['scale'])
        i.pop('scale')
        for s in scales:
            model_to_create.objects.update_or_create(
                scale=s,
                **i,
            )


def MMPI_motivators(apps, schema_editor):
    create_motivators_destructors(apps, schema_editor, sheet_name='Motivators')


def MMPI_destructors(apps, schema_editor):
    create_motivators_destructors(apps, schema_editor, sheet_name='Destructors')


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0022_mmpiscaledescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIMotivator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.PositiveIntegerField()),
                ('to_point', models.PositiveIntegerField()),
                ('motivator', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivators', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ мотиватор',
                'verbose_name_plural': 'ММИЛ мотиваторы',
            },
        ),
        migrations.CreateModel(
            name='MMPIDestructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.PositiveIntegerField()),
                ('to_point', models.PositiveIntegerField()),
                ('destructor', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destructors', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ деструктор',
                'verbose_name_plural': 'ММИЛ деструкторы',
            },
        ),
        migrations.RunPython(MMPI_motivators),
        migrations.RunPython(MMPI_destructors),
    ]
