# Generated by Django 3.1.4 on 2021-02-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0024_mmpiriskfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPICompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ММИЛ компетентность',
                'verbose_name_plural': 'ММИЛ компетентности',
            },
        ),
        migrations.CreateModel(
            name='MMPICompetenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ММИЛ категория компетентностей',
                'verbose_name_plural': 'ММИЛ категории компетентностей',
            },
        ),
        migrations.CreateModel(
            name='MMPICompetenceScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.PositiveIntegerField()),
                ('to_point', models.PositiveIntegerField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='candidate_tests.mmpicompetence')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='candidate_tests.mmpiscale')),
            ],
            options={
                'verbose_name': 'ММИЛ шкала компетентности',
                'verbose_name_plural': 'ММИЛ шкалы компетентности',
            },
        ),
        migrations.AddField(
            model_name='mmpicompetence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='candidate_tests.mmpicompetencecategory'),
        ),
    ]
