# Generated by Django 3.1.4 on 2021-02-16 20:00

from django.db import migrations, models
import django.db.models.deletion

from candidate_tests.utils import testing_data_parser


def create_MMPI_competences(apps, schema_editor):
    MMPICompetence = apps.get_model('candidate_tests', 'MMPICompetence')
    MMPICompetenceCategory = apps.get_model('candidate_tests', 'MMPICompetenceCategory')
    values = testing_data_parser.parse_MMPI_competences()

    for i in values:
        category, _ = MMPICompetenceCategory.objects.get_or_create(name=i['category'])
        i.pop('category')
        MMPICompetence.objects.update_or_create(category=category, **i)

def create_MMPI_competence_scale(apps, schema_editor):
    MMPICompetence = apps.get_model('candidate_tests', 'MMPICompetence')
    MMPIScale = apps.get_model('candidate_tests', 'MMPIScale')
    MMPICompetenceScale = apps.get_model('candidate_tests', 'MMPICompetenceScale')
    values = testing_data_parser.parse_MMPI_competences_scales()

    for i in values:
        competence, _ = MMPICompetence.objects.get_or_create(name=i['competence'])
        i.pop('competence')
        scale, _ = MMPIScale.objects.get_or_create(name=i['scale'])
        i.pop('scale')
        MMPICompetenceScale.objects.update_or_create(competence=competence, scale=scale, **i)

        

class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0025_auto_20210216_1856'),
    ]

    operations = [
        migrations.RunPython(create_MMPI_competences),
        migrations.RunPython(create_MMPI_competence_scale),
    ]
