# Generated by Django 3.1.4 on 2021-03-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210208_1146'),
        ('candidate_tests', '0030_testingsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('MMPI', 'MMPI'), ('NUMERIC_LOGIC', 'NUMERIC_LOGIC'), ('VERBAL_LOGIC', 'VERBAL_LOGIC'), ('NON_VERBAL_LOGIC', 'NON_VERBAL_LOGIC'), ('PROF_INTERESTS', 'PROF_INTERESTS')], max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('candidate_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_amount', to='users.candidatecreator')),
            ],
            options={
                'verbose_name': 'Количество отправок теста',
                'verbose_name_plural': 'Количества отправок тестов',
                'unique_together': {('candidate_creator', 'test')},
            },
        ),
    ]
