# Generated by Django 3.1.4 on 2021-03-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0031_testamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIUserRiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_risk_factors', to='candidate_tests.mmpiriskfactor')),
                ('testing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'ММИЛ фактор риска пользователя',
                'verbose_name_plural': 'ММИЛ факторы риска пользователей',
                'unique_together': {('risk_factor', 'testing_session')},
            },
        ),
    ]
