# Generated by Django 3.1.4 on 2021-03-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0032_mmpiuserriskfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmpiscaledescription',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='candidate_tests.mmpiscale'),
        ),
    ]
