# Generated by Django 3.1.4 on 2021-03-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0033_auto_20210303_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIUserCompetenceRecomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HIGHT', 'Высокоразвитые'), ('MEDIUM', 'Среднеразвитые'), ('LOW', 'Низкоразвитые')], max_length=100, unique=True)),
                ('recommendation', models.TextField()),
            ],
            options={
                'verbose_name': 'ММИЛ компетентности рекомендация',
                'verbose_name_plural': 'ММИЛ компетентности рекомендации',
            },
        ),
        migrations.CreateModel(
            name='MMPIUserCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HIGHT', 'Высокоразвитые'), ('MEDIUM', 'Среднеразвитые'), ('LOW', 'Низкоразвитые')], max_length=100)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_competences', to='candidate_tests.mmpicompetence')),
                ('testing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'ММИЛ компетентность пользователя',
                'verbose_name_plural': 'ММИЛ компетентности пользователей',
                'unique_together': {('testing_session', 'competence')},
            },
        ),
    ]
