# Generated by Django 3.1.4 on 2021-03-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0035_mmpiuserstresstolerance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmpidestructor',
            old_name='destructor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mmpimotivator',
            old_name='motivator',
            new_name='name',
        ),
        migrations.CreateModel(
            name='MMPIUserMotivator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_motivators', to='candidate_tests.mmpimotivator')),
                ('testing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivators', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'ММИЛ мотиватор пользователя',
                'verbose_name_plural': 'ММИЛ мотиваторы пользователей',
            },
        ),
        migrations.CreateModel(
            name='MMPIUserDestructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_destructors', to='candidate_tests.mmpidestructor')),
                ('testing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destructors', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'ММИЛ деструктор пользователя',
                'verbose_name_plural': 'ММИЛ деструкторы пользователей',
            },
        ),
    ]
