# Generated by Django 3.1.4 on 2021-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0037_mmpiuserteamrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmpitestinguserrawpointsresult',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mmpitestingusertpointsresult',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
