# Generated by Django 3.1.4 on 2021-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0039_auto_20210305_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonverballogicansweroption',
            name='title',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
