# Generated by Django 3.1.4 on 2021-03-11 20:20

from django.db import migrations, models
import django.db.models.deletion

from candidate_tests.utils import testing_data_parser


def MMPI_leadership_styles(apps, schema_editor):
    MMPILeadershipStyle = apps.get_model('candidate_tests', 'MMPILeadershipStyle')
    values = testing_data_parser.parse_MMPI_leadership_styles()

    for v in values:
        MMPILeadershipStyle.objects.update_or_create(**v)


def MMPI_leadership_style_scales(apps, schema_editor):
    MMPILeadershipStyle = apps.get_model('candidate_tests', 'MMPILeadershipStyle')
    MMPILeadershipStyleScale = apps.get_model('candidate_tests', 'MMPILeadershipStyleScale')
    MMPIScale = apps.get_model('candidate_tests', 'MMPIScale')
    values = testing_data_parser.parse_MMPI_leadership_style_scales()

    for v in values:
        style = MMPILeadershipStyle.objects.get(name=v['style'])
        v.pop('style')
        scale = MMPIScale.objects.get(name=v['scale'])
        v.pop('scale')
        MMPILeadershipStyleScale.objects.update_or_create(style=style, scale=scale, **v)


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0041_auto_20210310_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPILeadershipStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ММИЛ стиль руководства',
                'verbose_name_plural': 'ММИЛ стили руководства',
            },
        ),
        migrations.CreateModel(
            name='MMPILeadershipStyleScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.PositiveIntegerField()),
                ('to_point', models.PositiveIntegerField()),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_styles', to='candidate_tests.mmpiscale')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='candidate_tests.mmpileadershipstyle')),
            ],
            options={
                'verbose_name': 'ММИЛ стиль руководства шкала',
                'verbose_name_plural': 'ММИЛ стили руководства шкалы',
                'unique_together': {('style', 'scale')},
            },
        ),
        migrations.RunPython(MMPI_leadership_styles),
        migrations.RunPython(MMPI_leadership_style_scales),
    ]
