# Generated by Django 3.1.4 on 2021-03-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0042_mmpileadershipstyle_mmpileadershipstylescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIUserLeadershipStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_leadership_styles', to='candidate_tests.mmpileadershipstyle')),
                ('testing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_styles', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'ММИЛ стиль руководства пользователя',
                'verbose_name_plural': 'ММИЛ стили руководства пользователей',
                'unique_together': {('testing_session', 'style')},
            },
        ),
    ]
