# Generated by Django 3.1.4 on 2021-03-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0043_mmpiuserleadershipstyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testingsession',
            name='tests',
        ),
        migrations.CreateModel(
            name='TestingSessionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MMPI', 'MMPI'), ('NUMERIC_LOGIC', 'NUMERIC_LOGIC'), ('VERBAL_LOGIC', 'VERBAL_LOGIC'), ('NON_VERBAL_LOGIC', 'NON_VERBAL_LOGIC'), ('PROF_INTERESTS', 'PROF_INTERESTS')], max_length=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_SEND', 'NOT_SEND'), ('RESEND', 'RESEND'), ('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('NOT_COMPLETED', 'NOT_COMPLETED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='candidate_tests.testingsession')),
            ],
            options={
                'verbose_name': 'Cессия тестирования тест',
                'verbose_name_plural': 'Cессии тестирования тесты',
            },
        ),
    ]
