# Generated by Django 3.1.4 on 2021-03-15 17:25

from django.db import migrations, models

from candidate_tests.utils import testing_data_parser


def MMPI_scales_number(apps, schema_editor):
    MMPIScale = apps.get_model('candidate_tests', 'MMPIScale')
    scales = testing_data_parser.parse_json_file('MMPI_scales.json')

    for scale in MMPIScale.objects.all():
        number = scales[scale.name]['number']
        scale.number = number
        scale.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0044_auto_20210315_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmpiscale',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(MMPI_scales_number),
    ]
