# Generated by Django 3.1.4 on 2021-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_tests', '0048_auto_20210527_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmpiquestion',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nonverballogicansweroption',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nonverballogicquestion',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='numericlogicquestion',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='profinterestsquestion',
            old_name='number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='verballogicquestion',
            old_name='number',
            new_name='id',
        ),
    ]
