# Generated by Django 3.1.4 on 2021-01-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210115_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='users.manager'),
            preserve_default=False,
        ),
    ]
