# Generated by Django 3.1.4 on 2021-01-22 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidate_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='taxpayer_id_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='ИНН'),
        ),
    ]
