# Generated by Django 3.1.4 on 2021-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
