# Generated by Django 3.1.4 on 2021-05-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_candidate_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='compony',
            new_name='company',
        ),
    ]
